@startuml DriveHub

' Clases

class GestorDeReserva {
    - kilometrajeInicial: number
    - kilometrajeFinal: number
    - distanciaRecorrida: number
    - cliente: Cliente
    - vehiculo: Vehiculo

    + getters()
    + setters()
    + tarifa(): number
}

abstract class Persona {
    - nombre: string
    - apellido: string
    - dni: number

    + getters()
    + setters()
}

class Cliente {

}


abstract class Vehiculo {
    # patente: string
    # kilometraje: number
    # tarifaBase: number

    + getters()
    + setters()

}

class Sedan {

}

class Compacto {

}

class SUV {

}

interface Tarifa {
    + calculoTarifa(): number
}

abstract class Estado {
    - fechaInicio: date
    - fechaFin: date
    - vehiculo: map<matricula: string, Vehiculo>

    + getters()
    + setters()
}

class Reserva {
    
}

class NecesitaLimpieza {
    
}

class Mantenimiento {
    - costo: number
    
}

class Disponible {
    
}

' Relaciones

Persona <|-d- Cliente

Tarifa <|.u. Sedan
Tarifa <|.u. Compacto
Tarifa <|.u. SUV

Vehiculo <|-d- Sedan
Vehiculo <|-d- Compacto
Vehiculo <|-d- SUV

GestorDeReserva *-l- Vehiculo
GestorDeReserva *-r- Cliente

Estado *-r- Vehiculo

Estado <|-d- Reserva
Estado <|-d- NecesitaLimpieza
Estado <|-d- Mantenimiento
Estado <|-d- Disponible



@enduml
