@startuml DriveHub

' Clases

class GestorDeReserva {
    - kilometrajeInicial: number
    - kilometrajeFinal: number
    - distanciaRecorrida: number
    - cliente: Cliente
    - vehiculo: Vehiculo
    - vehiculoDevuelto: boolean;

    + getters()
    + setters()
    + tarifa(tarifaInicial, distancia)
}

abstract class Persona {
    - nombre: string
    - apellido: string
    - dni: number

    + getters()
    + setters()
}

class Cliente {

}


abstract class Vehiculo {
    # patente: string
    #kilometraje: number
    # tarifaBase: number
    - disponible: bool
    # estado: Estado

    + getters()
    + setters()

}

class Sedan {

}

class Compacto {

}

class SUV {

}

interface Tarifa {

}

abstract class Estado {
    - fechaInicio: number
    - fechaFin: number

    + getters()
    + setters()
}

class Reserva {
    - cliente: Cliente
}

class NecesitaLimpieza {
    - distanciaRecorrida: number
}

class Mantenimiento {
    - costo: number
    - fecha: number
}

' Relaciones

Persona <|-d- Cliente

Tarifa <|.u. Sedan
Tarifa <|.u. Compacto
Tarifa <|.u. SUV

Vehiculo <|-d- Sedan
Vehiculo <|-d- Compacto
Vehiculo <|-d- SUV

GestorDeReserva *-l- Vehiculo
GestorDeReserva *-r- Cliente

Vehiculo *-l- Estado

Estado <|-d- Reserva
Estado <|-d- NecesitaLimpieza
Estado <|-d- Mantenimiento



@enduml
